### ISSUE TITLE
Back to search button

### ISSUE THREAD

**Issue by James-Millan** [spe-uob/2021-HiddenMuseum#91]
When you have clicked on an item, there should be a button in the nav bar that takes you back to the search results you previously searched for.

**Comment by baconsenpaii** [comment]
Would require some kind of data persistence (probably storing the search parameters in the URL for the item lookups), but should be possible.

**Comment by James-Millan** [comment]
> Would require some kind of data persistence (probably storing the search parameters in the URL for the item lookups), but should be possible.

I was thinking we could just add a search parameters attribute to the model in LookupController
